[package]
name = "bevy_girk_wiring_server"
version.workspace = true
edition.workspace = true

[lib]
test    = false
doctest = false

[features]
test = [
    "memory_transport",
    "native_transport",
    "wasm_transport"
]

memory_transport = [
    "bevy_renet2/memory_transport",
    "bevy_replicon_renet2/memory_transport",
    "renet2/memory_transport"
]
native_transport = [
    "bevy_renet2/native_transport",
    "bevy_replicon_renet2/native_transport",
    "renet2/native_transport"
]
wasm_transport = [
    "bevy_renet2/wt_server_transport",
    "bevy_replicon_renet2/wt_server_transport",
    "renet2/wt_server_transport",
    "dep:enfync",
    "enfync/builtin"  #todo: this brings in tokio dependency
]

[dependencies]
bevy                     = { workspace = true }
bevy_replicon            = { workspace = true }
bevy_replicon_attributes = { workspace = true }
bincode                  = { workspace = true }
bytes                    = { workspace = true }
iyes_progress            = { workspace = true }
serde                    = { workspace = true }
tracing                  = { workspace = true }
ordered-multimap         = { version = "0.7" }
wasm-timer               = { version = "0.2" }

enfync = { workspace = true, optional = true }

bevy_girk_game_instance = { path = "../bevy_girk_game_instance" }
bevy_girk_game_fw = { path = "../bevy_girk_game_fw" }
bevy_girk_utils = { path = "../bevy_girk_utils" }
bevy_girk_wiring_common = { path = "../bevy_girk_wiring_common" }

bevy_renet2 = { workspace = true, features = ["serde"] }
bevy_replicon_renet2 = { workspace = true, features = ["renet_serde"] }
renet2 = { workspace = true, features = ["serde"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rand = { version = "0.8" }
