[package]
name = "bevy_girk_wiring_common"
version.workspace = true
edition.workspace = true

[lib]
test    = false
doctest = false

[features]
memory_transport = ["renet2/memory_transport"]

[dependencies]
bevy                 = { workspace = true }
bevy_cobweb          = { workspace = true }
bevy_renet2          = { workspace = true, features = ["transport", "serde"] }
bevy_replicon        = { workspace = true }
bevy_replicon_renet2 = { workspace = true }
bevy_simplenet       = { workspace = true }
serde                = { workspace = true }
tracing              = { workspace = true }
